# Generated by Django 4.1 on 2022-08-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=25)),
                ('cp', models.IntegerField()),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bar', models.CharField(max_length=30)),
                ('cuit', models.IntegerField()),
                ('provincia', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=45)),
                ('paginaweb', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('rubro', models.CharField(max_length=30)),
                ('slogan', models.CharField(max_length=100)),
                ('antiguedad_anios', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('variedad', models.CharField(max_length=20)),
                ('contenido_ml', models.IntegerField()),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
    ]
