# Generated by Django 4.1 on 2022-08-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppThatBeer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patrocinadores',
            new_name='Patrocinador',
        ),
    ]
