# Generated by Django 4.1 on 2022-08-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppThatBeer', '0002_rename_patrocinadores_patrocinador'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='NA', max_length=150),
            preserve_default=False,
        ),
    ]
