# Generated by Django 4.1 on 2022-08-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppThatBeer', '0003_producto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribuidor',
            old_name='nombre_bar',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='distribuidor',
            name='paginaweb',
        ),
        migrations.RemoveField(
            model_name='patrocinador',
            name='email',
        ),
        migrations.AddField(
            model_name='distribuidor',
            name='descuento',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distribuidor',
            name='web',
            field=models.URLField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='web',
            field=models.URLField(default=1234),
            preserve_default=False,
        ),
    ]
